# Function that makes Row echelon form

In [1]:
def row_echelon(A):
    """ Return Row Echelon Form of matrix A """

    # if matrix A has no columns or rows,
    # it is already in REF, so we return itself
    r, c = A.shape
    if r == 0 or c == 0:
        return A

    # we search for non-zero element in the first column
    for i in range(len(A)):
        if A[i,0] != 0:
            break
    else:
        # if all elements in the first column is zero,
        # we perform REF on matrix from second column
        B = row_echelon(A[:,1:])
        # and then add the first zero-column back
        return np.hstack([A[:,:1], B])

    # if non-zero element happens not in the first row,
    # we switch rows
    if i > 0:
        ith_row = A[i].copy()
        A[i] = A[0]
        A[0] = ith_row

    # we divide first row by first element in it
    A[0] = A[0] / A[0,0]
    # we subtract all subsequent rows with first row (it has 1 now as first element)
    # multiplied by the corresponding element in the first column
    A[1:] -= A[0] * A[1:,0:1]

    # we perform REF on matrix from second row, from second column
    B = row_echelon(A[1:,1:])

    # we add first row and first (zero) column, and return
    return np.vstack([A[:1], np.hstack([A[1:,:1], B]) ])

# SVD

In [2]:
from numpy.linalg import eig
import copy
import numpy as np

In [3]:
test = np.array(range(1,13)).reshape(3,4)

In [4]:
row_echelon(copy.copy(test)) # rank=2 -> #eigenvalue = 2

array([[1, 2, 3, 4],
       [0, 1, 2, 3],
       [0, 0, 0, 0]])

In [5]:
sym_U = np.matmul(test,test.T)
sym_U

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [6]:
sym_V = np.matmul(test.T, test)
sym_V

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

In [7]:
evu, U = eig(sym_U)
print(evu)
print()
print(U)

[6.47032607e+02 2.96739296e+00 2.51477877e-14]

[[-0.20673589 -0.88915331  0.40824829]
 [-0.51828874 -0.25438183 -0.81649658]
 [-0.82984158  0.38038964  0.40824829]]


In [8]:
evv, V = eig(sym_V)
print(evv)
print()
print(V)

[ 6.47032607e+02  2.96739296e+00 -4.56921881e-14  1.19506152e-15]

[[-0.40361757  0.73286619  0.53729568 -0.07560543]
 [-0.46474413  0.28984978 -0.79567348 -0.30353298]
 [-0.52587069 -0.15316664 -0.02054008  0.83388224]
 [-0.58699725 -0.59618305  0.27891788 -0.45474384]]


In [9]:
sqrt_evv = np.sqrt(evv)
sqrt_evu = np.sqrt(evu)
print(np.sqrt(evv))
print(np.sqrt(evu))

[2.54368356e+01 1.72261225e+00            nan 3.45696618e-08]
[2.54368356e+01 1.72261225e+00 1.58580540e-07]


C:\Users\rkske\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.
C:\Users\rkske\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in sqrt
  This is separate from the ipykernel package so we can avoid doing imports until


In [10]:
print(U)

[[-0.20673589 -0.88915331  0.40824829]
 [-0.51828874 -0.25438183 -0.81649658]
 [-0.82984158  0.38038964  0.40824829]]


In [11]:
S = np.array([[sqrt_evv[0],0,0,0],[0,sqrt_evv[1],0,0,],[0,0,0,0]])
S

array([[25.43683563,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.72261225,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ]])

In [12]:
print(V)

[[-0.40361757  0.73286619  0.53729568 -0.07560543]
 [-0.46474413  0.28984978 -0.79567348 -0.30353298]
 [-0.52587069 -0.15316664 -0.02054008  0.83388224]
 [-0.58699725 -0.59618305  0.27891788 -0.45474384]]


In [13]:
SVD_A = np.matmul(U,np.matmul(S,V.T))
epsilon = +0.001
SVD_A = (SVD_A + epsilon).astype(int)
SVD_A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])